name: pif_paf_pouf
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  go_router: ^15.1.1
  gap: ^3.0.1
  firebase_database: ^11.3.4
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  shared_preferences: ^2.5.3
  nearby_connections: ^4.3.0
  sensors_plus: ^4.0.2
  vibration: ^1.8.3
  permission_handler: ^12.0.0+1
  location: ^5.0.0
  device_info_plus: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png" # Replace with your icon path

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Chewy
      fonts:
        - asset: assets/fonts/Chewy-Regular.ttf
          
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/logo.png